services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    tty: true
    volumes:
      - ./inusta:/var/www/inusta
      - ./inusta/storage/app/public:/var/www/inusta/storage/app/public
    networks:
      - laravel
    working_dir: /var/www/inusta

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./inusta/public:/var/www/inusta/public
      - ./inusta/storage/app/public:/var/www/inusta/public/storage
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mariadb:latest
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inusta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata: